"""alterando relacionamento aluno x plano x matricula

Revision ID: 11c72c813e9c
Revises: 5763023c7e9a
Create Date: 2025-02-06 14:40:30.908182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c72c813e9c'
down_revision = '5763023c7e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_plano')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno_plano',
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('plano_id', sa.INTEGER(), nullable=False),
    sa.Column('data_matricula', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'plano_id')
    )
    # ### end Alembic commands ###
