"""add de colunas em aluno

Revision ID: 1db39efe389a
Revises: 11c72c813e9c
Create Date: 2025-02-13 13:08:30.366074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db39efe389a'
down_revision = '11c72c813e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('responsavel', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contato_emergencia', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('contato_emergencia')
        batch_op.drop_column('responsavel')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
