"""mudança de relacionamento e add Turma

Revision ID: 22cebb08a30a
Revises: 62ee4cb03d71
Create Date: 2025-01-29 18:49:05.757587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cebb08a30a'
down_revision = '62ee4cb03d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_plano')
    op.drop_table('aluno_modalidade')
    op.drop_table('conta_pagar')
    op.drop_table('mensalidade')
    op.drop_table('permissao')
    op.drop_table('professor')
    op.drop_table('modalidade')
    op.drop_table('usuario_permissao')
    op.drop_table('aluno')
    op.drop_table('plano')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plano',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('valor_mensal', sa.FLOAT(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuario_permissao',
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('permissao_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permissao_id')
    )
    op.create_table('modalidade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
    sa.Column('especialidade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('permissao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('mensalidade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('mes_referencia', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('data_pagamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_pagar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data_vencimento', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_modalidade',
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('modalidade_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'modalidade_id')
    )
    op.create_table('aluno_plano',
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('plano_id', sa.INTEGER(), nullable=False),
    sa.Column('data_matricula', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'plano_id')
    )
    # ### end Alembic commands ###
