"""matricula

Revision ID: 5763023c7e9a
Revises: e1357a3c3a5b
Create Date: 2025-02-05 22:15:48.261917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5763023c7e9a'
down_revision = 'e1357a3c3a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensalidade')
    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.drop_column('data_vencimento')

    op.create_table('mensalidade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('mes_referencia', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('data_pagamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
