"""Adicionando campo ativo na classe aluno

Revision ID: e1357a3c3a5b
Revises: b3b207f72b51
Create Date: 2025-02-05 20:51:17.494376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1357a3c3a5b'
down_revision = 'b3b207f72b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
